spring.application.name=api-formulario
# ======================================================
# CONFIGURACIÓN DE BASE DE DATOS MYSQL
# ======================================================
spring.datasource.url=jdbc:mysql://localhost:3306/contratacionCrunchyroll?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=tu_contraseña
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ======================================================
# CONFIGURACIÓN JPA / HIBERNATE
# ======================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hiberjate.format_sql=true